# Generated by Django 3.0.3 on 2020-06-20 06:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200620_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 20, 6, 56, 53, 860673, tzinfo=utc)),
        ),
    ]
