# Generated by Django 3.0.3 on 2020-06-20 07:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200620_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 20, 7, 14, 39, 990793, tzinfo=utc)),
        ),
    ]
